// wgpu_backend.cpp — WebGPU backend implementation for Spectra.
//
// Compiles only when SPECTRA_USE_WEBGPU is defined.  Depends on webgpu.h
// (Dawn native or the Emscripten-provided <emscripten/html5_webgpu.h>).

#ifdef SPECTRA_USE_WEBGPU

    #include "wgpu_backend.hpp"

    #include <spectra/logger.hpp>

    #include <cassert>
    #include <cstring>
    #include <stdexcept>
    #include <string>

    // Include the platform-appropriate WebGPU header.
    #ifdef __EMSCRIPTEN__
        #include <emscripten/html5_webgpu.h>
        #include <webgpu/webgpu.h>
    #else
        #include <webgpu/webgpu.h>

        // GLFW native access for platform surface creation.
        #ifdef SPECTRA_USE_GLFW
            #define GLFW_INCLUDE_NONE
            #include <GLFW/glfw3.h>
            #ifdef __linux__
                #define GLFW_EXPOSE_NATIVE_X11
            #elif defined(_WIN32)
                #define GLFW_EXPOSE_NATIVE_WIN32
            #elif defined(__APPLE__)
                #define GLFW_EXPOSE_NATIVE_COCOA
            #endif
            #include <GLFW/glfw3native.h>
        #endif
    #endif

    // Embedded WGSL shader sources (generated by cmake/EmbedWGSLShaders.cmake).
    #include "shader_wgsl.hpp"

    // ── Helper: convert a C string literal to WGPUStringView ─────────────────
    #define WGPU_LABEL(s)                      \
        WGPUStringView                         \
        {                                      \
            .data = (s), .length = WGPU_STRLEN \
        }

namespace spectra
{

// ─── Alignment helper ─────────────────────────────────────────────────────────

static constexpr uint32_t WGPU_UBO_ALIGN      = 256;
static constexpr uint32_t WGPU_UBO_RING_SLOTS = 64;
static constexpr uint32_t WGPU_FRAME_UBO_SLOT_SIZE =
    (sizeof(FrameUBO) + WGPU_UBO_ALIGN - 1) & ~(WGPU_UBO_ALIGN - 1);
static constexpr uint64_t WGPU_FRAME_UBO_RING_SIZE =
    static_cast<uint64_t>(WGPU_FRAME_UBO_SLOT_SIZE) * WGPU_UBO_RING_SLOTS;

// ─── Construction / destruction ───────────────────────────────────────────────

WebGPUBackend::WebGPUBackend() = default;

WebGPUBackend::~WebGPUBackend()
{
    shutdown();
}

// ─── Lifecycle ────────────────────────────────────────────────────────────────

bool WebGPUBackend::init(bool headless)
{
    headless_ = headless;

    // Create WebGPU instance.
    WGPUInstanceDescriptor inst_desc{};
    inst_desc.nextInChain = nullptr;
    instance_             = wgpuCreateInstance(&inst_desc);
    if (!instance_)
    {
        SPECTRA_LOG_ERROR("webgpu", "wgpuCreateInstance failed");
        return false;
    }

    if (!request_adapter())
        return false;

    if (!request_device())
        return false;

    queue_ = wgpuDeviceGetQueue(device_);

    create_bind_group_layouts();
    create_pipeline_layouts();

    if (!create_default_resources())
        return false;

    return true;
}

void WebGPUBackend::shutdown()
{
    // Release all cached bind groups for buffers and textures.
    for (auto& [id, entry] : buffers_)
    {
        if (entry.bind_group)
            wgpuBindGroupRelease(entry.bind_group);
        if (entry.buffer)
            wgpuBufferDestroy(entry.buffer);
    }
    buffers_.clear();

    for (auto& [id, entry] : textures_)
    {
        if (entry.bind_group)
            wgpuBindGroupRelease(entry.bind_group);
        if (entry.sampler)
            wgpuSamplerRelease(entry.sampler);
        if (entry.view)
            wgpuTextureViewRelease(entry.view);
        if (entry.texture)
            wgpuTextureDestroy(entry.texture);
    }
    textures_.clear();

    for (auto& [id, entry] : pipelines_)
    {
        if (entry.pipeline)
            wgpuRenderPipelineRelease(entry.pipeline);
    }
    pipelines_.clear();

    if (frame_bind_group_)
    {
        wgpuBindGroupRelease(frame_bind_group_);
        frame_bind_group_ = nullptr;
    }
    if (series_pc_buf_)
    {
        wgpuBufferDestroy(series_pc_buf_);
        series_pc_buf_ = nullptr;
    }
    if (frame_ubo_ring_)
    {
        wgpuBufferDestroy(frame_ubo_ring_);
        frame_ubo_ring_ = nullptr;
    }

    if (pl_texture_)
    {
        wgpuPipelineLayoutRelease(pl_texture_);
        pl_texture_ = nullptr;
    }
    if (pl_vertex_)
    {
        wgpuPipelineLayoutRelease(pl_vertex_);
        pl_vertex_ = nullptr;
    }
    if (pl_ssbo_)
    {
        wgpuPipelineLayoutRelease(pl_ssbo_);
        pl_ssbo_ = nullptr;
    }

    if (bgl_group1_texture_)
    {
        wgpuBindGroupLayoutRelease(bgl_group1_texture_);
        bgl_group1_texture_ = nullptr;
    }
    if (bgl_group1_ssbo_)
    {
        wgpuBindGroupLayoutRelease(bgl_group1_ssbo_);
        bgl_group1_ssbo_ = nullptr;
    }
    if (bgl_group0_)
    {
        wgpuBindGroupLayoutRelease(bgl_group0_);
        bgl_group0_ = nullptr;
    }

    if (offscreen_depth_view_)
    {
        wgpuTextureViewRelease(offscreen_depth_view_);
        offscreen_depth_view_ = nullptr;
    }
    if (offscreen_view_)
    {
        wgpuTextureViewRelease(offscreen_view_);
        offscreen_view_ = nullptr;
    }
    if (offscreen_depth_)
    {
        wgpuTextureDestroy(offscreen_depth_);
        offscreen_depth_ = nullptr;
    }
    if (offscreen_color_)
    {
        wgpuTextureDestroy(offscreen_color_);
        offscreen_color_ = nullptr;
    }

    if (surface_)
    {
        if (sc_width_ > 0 && sc_height_ > 0)
            wgpuSurfaceUnconfigure(surface_);
        wgpuSurfaceRelease(surface_);
        surface_ = nullptr;
    }

    // Release the queue before the device — both reference the same
    // internal Dawn structures.
    if (queue_)
    {
        wgpuQueueRelease(queue_);
        queue_ = nullptr;
    }

    if (device_)
    {
        if (headless_)
        {
            // Headless mode: no X11/surface involvement, safe to destroy.
            wgpuDeviceDestroy(device_);
            wgpuDeviceRelease(device_);
        }
        else
        {
            // Windowed mode: skip explicit device destruction.
            // Dawn's FencedDeleter::UpdateCompletedSerialTo triggers the
            // NVIDIA Vulkan driver's GLX lazy-init path which calls
            // _XSend on a stale X11 connection, causing a segfault.
            // Both wgpuDeviceDestroy and wgpuDeviceRelease lead to the
            // same DeviceBase::Destroy codepath.  The OS reclaims all GPU
            // and X11 resources on process exit.
        }
        device_ = nullptr;
    }
    if (adapter_)
    {
        wgpuAdapterRelease(adapter_);
        adapter_ = nullptr;
    }
    if (instance_)
    {
        wgpuInstanceRelease(instance_);
        instance_ = nullptr;
    }
}

void WebGPUBackend::wait_idle()
{
    // Poll the instance to process all pending operations.
    if (instance_)
        wgpuInstanceProcessEvents(instance_);
}

// ─── Adapter / device request helpers ────────────────────────────────────────

bool WebGPUBackend::request_adapter()
{
    struct Result
    {
        WGPUAdapter adapter = nullptr;
        bool        done    = false;
        bool        ok      = false;
    } result;

    WGPURequestAdapterOptions opts{};
    opts.powerPreference      = WGPUPowerPreference_HighPerformance;
    opts.forceFallbackAdapter = false;

    WGPURequestAdapterCallbackInfo cb_info{};
    cb_info.mode     = WGPUCallbackMode_AllowSpontaneous;
    cb_info.callback = [](WGPURequestAdapterStatus status,
                          WGPUAdapter              adapter,
                          WGPUStringView /*msg*/,
                          void* userdata1,
                          void* /*userdata2*/)
    {
        auto* r    = static_cast<Result*>(userdata1);
        r->ok      = (status == WGPURequestAdapterStatus_Success);
        r->adapter = adapter;
        r->done    = true;
    };
    cb_info.userdata1 = &result;

    wgpuInstanceRequestAdapter(instance_, &opts, cb_info);

    #ifdef __EMSCRIPTEN__
    // Emscripten: the callback fires asynchronously; we cannot spin here.
    (void)result;
    device_ = emscripten_webgpu_get_device();
    if (!device_)
    {
        SPECTRA_LOG_ERROR("webgpu", "emscripten_webgpu_get_device failed");
        return false;
    }
    return true;
    #else
    // Dawn native: process events until the callback fires.
    while (!result.done)
        wgpuInstanceProcessEvents(instance_);

    if (!result.ok || !result.adapter)
    {
        SPECTRA_LOG_ERROR("webgpu", "wgpuInstanceRequestAdapter failed");
        return false;
    }
    adapter_ = result.adapter;
    return true;
    #endif
}

bool WebGPUBackend::request_device()
{
    #ifdef __EMSCRIPTEN__
    // Device already obtained via emscripten_webgpu_get_device() in request_adapter.
    return device_ != nullptr;
    #else
    struct Result
    {
        WGPUDevice device = nullptr;
        bool       done   = false;
        bool       ok     = false;
    } result;

    WGPUDeviceDescriptor desc{};
    desc.label              = WGPU_LABEL("SpectraDevice");
    desc.defaultQueue.label = WGPU_LABEL("SpectraQueue");

    // Set up error callback for validation errors.
    desc.uncapturedErrorCallbackInfo.callback = [](WGPUDevice const* /*device*/,
                                                   WGPUErrorType  type,
                                                   WGPUStringView message,
                                                   void* /*userdata1*/,
                                                   void* /*userdata2*/)
    {
        SPECTRA_LOG_ERROR("webgpu",
                          "Dawn error type={}: {}",
                          static_cast<int>(type),
                          std::string(message.data, message.length));
    };

    desc.deviceLostCallbackInfo.callback = [](WGPUDevice const* /*device*/,
                                              WGPUDeviceLostReason reason,
                                              WGPUStringView       message,
                                              void* /*userdata1*/,
                                              void* /*userdata2*/)
    {
        SPECTRA_LOG_ERROR("webgpu",
                          "Dawn device lost reason={}: {}",
                          static_cast<int>(reason),
                          std::string(message.data, message.length));
    };

    WGPURequestDeviceCallbackInfo cb_info{};
    cb_info.mode     = WGPUCallbackMode_AllowSpontaneous;
    cb_info.callback = [](WGPURequestDeviceStatus status,
                          WGPUDevice              device,
                          WGPUStringView /*msg*/,
                          void* userdata1,
                          void* /*userdata2*/)
    {
        auto* r   = static_cast<Result*>(userdata1);
        r->ok     = (status == WGPURequestDeviceStatus_Success);
        r->device = device;
        r->done   = true;
    };
    cb_info.userdata1 = &result;

    wgpuAdapterRequestDevice(adapter_, &desc, cb_info);

    while (!result.done)
        wgpuInstanceProcessEvents(instance_);

    if (!result.ok || !result.device)
    {
        SPECTRA_LOG_ERROR("webgpu", "wgpuAdapterRequestDevice failed");
        return false;
    }
    device_ = result.device;
    return true;
    #endif
}

// ─── Bind group layout creation ───────────────────────────────────────────────

void WebGPUBackend::create_bind_group_layouts()
{
    // Group 0: FrameUBO (uniform, dynamic offset) + SeriesPC (uniform)
    {
        WGPUBindGroupLayoutEntry entries[2]{};

        // binding 0: FrameUBO with dynamic offset
        entries[0].binding                 = 0;
        entries[0].visibility              = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
        entries[0].buffer.type             = WGPUBufferBindingType_Uniform;
        entries[0].buffer.hasDynamicOffset = true;
        entries[0].buffer.minBindingSize   = sizeof(FrameUBO);

        // binding 1: SeriesPC (no dynamic offset)
        entries[1].binding                 = 1;
        entries[1].visibility              = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
        entries[1].buffer.type             = WGPUBufferBindingType_Uniform;
        entries[1].buffer.hasDynamicOffset = false;
        entries[1].buffer.minBindingSize   = sizeof(SeriesPushConstants);

        WGPUBindGroupLayoutDescriptor desc{};
        desc.label      = WGPU_LABEL("BGL_Group0");
        desc.entryCount = 2;
        desc.entries    = entries;
        bgl_group0_     = wgpuDeviceCreateBindGroupLayout(device_, &desc);
    }

    // Group 1 (SSBO variant): one read-only storage buffer
    {
        WGPUBindGroupLayoutEntry entry{};
        entry.binding               = 0;
        entry.visibility            = WGPUShaderStage_Vertex;
        entry.buffer.type           = WGPUBufferBindingType_ReadOnlyStorage;
        entry.buffer.minBindingSize = 8;   // at least one vec2

        WGPUBindGroupLayoutDescriptor desc{};
        desc.label       = WGPU_LABEL("BGL_Group1_SSBO");
        desc.entryCount  = 1;
        desc.entries     = &entry;
        bgl_group1_ssbo_ = wgpuDeviceCreateBindGroupLayout(device_, &desc);
    }

    // Group 1 (texture variant): texture_2d + sampler
    {
        WGPUBindGroupLayoutEntry entries[2]{};

        entries[0].binding               = 0;
        entries[0].visibility            = WGPUShaderStage_Fragment;
        entries[0].texture.sampleType    = WGPUTextureSampleType_Float;
        entries[0].texture.viewDimension = WGPUTextureViewDimension_2D;
        entries[0].texture.multisampled  = false;

        entries[1].binding      = 1;
        entries[1].visibility   = WGPUShaderStage_Fragment;
        entries[1].sampler.type = WGPUSamplerBindingType_Filtering;

        WGPUBindGroupLayoutDescriptor desc{};
        desc.label          = WGPU_LABEL("BGL_Group1_Texture");
        desc.entryCount     = 2;
        desc.entries        = entries;
        bgl_group1_texture_ = wgpuDeviceCreateBindGroupLayout(device_, &desc);
    }
}

void WebGPUBackend::create_pipeline_layouts()
{
    // pl_ssbo_: group 0 + group 1 (storage)
    {
        WGPUBindGroupLayout          bgls[] = {bgl_group0_, bgl_group1_ssbo_};
        WGPUPipelineLayoutDescriptor desc{};
        desc.label                = WGPU_LABEL("PL_SSBO");
        desc.bindGroupLayoutCount = 2;
        desc.bindGroupLayouts     = bgls;
        pl_ssbo_                  = wgpuDeviceCreatePipelineLayout(device_, &desc);
    }

    // pl_vertex_: group 0 only
    {
        WGPUPipelineLayoutDescriptor desc{};
        desc.label                = WGPU_LABEL("PL_Vertex");
        desc.bindGroupLayoutCount = 1;
        desc.bindGroupLayouts     = &bgl_group0_;
        pl_vertex_                = wgpuDeviceCreatePipelineLayout(device_, &desc);
    }

    // pl_texture_: group 0 + group 1 (texture)
    {
        WGPUBindGroupLayout          bgls[] = {bgl_group0_, bgl_group1_texture_};
        WGPUPipelineLayoutDescriptor desc{};
        desc.label                = WGPU_LABEL("PL_Texture");
        desc.bindGroupLayoutCount = 2;
        desc.bindGroupLayouts     = bgls;
        pl_texture_               = wgpuDeviceCreatePipelineLayout(device_, &desc);
    }
}

bool WebGPUBackend::create_default_resources()
{
    // FrameUBO ring buffer
    {
        WGPUBufferDescriptor desc{};
        desc.label            = WGPU_LABEL("FrameUBO_Ring");
        desc.usage            = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
        desc.size             = WGPU_FRAME_UBO_RING_SIZE;
        desc.mappedAtCreation = false;
        frame_ubo_ring_       = wgpuDeviceCreateBuffer(device_, &desc);
        if (!frame_ubo_ring_)
            return false;
    }

    // SeriesPC small uniform buffer
    {
        WGPUBufferDescriptor desc{};
        desc.label = WGPU_LABEL("SeriesPC");
        desc.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
        // Round up to 256-byte alignment
        desc.size = (sizeof(SeriesPushConstants) + WGPU_UBO_ALIGN - 1) & ~(WGPU_UBO_ALIGN - 1u);
        desc.mappedAtCreation = false;
        series_pc_buf_        = wgpuDeviceCreateBuffer(device_, &desc);
        if (!series_pc_buf_)
            return false;
    }

    // Create the group-0 bind group (frame UBO + series PC).
    {
        WGPUBindGroupEntry entries[2]{};

        entries[0].binding = 0;
        entries[0].buffer  = frame_ubo_ring_;
        entries[0].offset  = 0;
        entries[0].size    = WGPU_FRAME_UBO_SLOT_SIZE;

        entries[1].binding = 1;
        entries[1].buffer  = series_pc_buf_;
        entries[1].offset  = 0;
        entries[1].size =
            (sizeof(SeriesPushConstants) + WGPU_UBO_ALIGN - 1) & ~(WGPU_UBO_ALIGN - 1u);

        WGPUBindGroupDescriptor desc{};
        desc.label        = WGPU_LABEL("BG_Group0");
        desc.layout       = bgl_group0_;
        desc.entryCount   = 2;
        desc.entries      = entries;
        frame_bind_group_ = wgpuDeviceCreateBindGroup(device_, &desc);
        if (!frame_bind_group_)
            return false;
    }

    return true;
}

// ─── Surface / swapchain ──────────────────────────────────────────────────────

bool WebGPUBackend::create_surface(void* native_window)
{
    if (!instance_ || !native_window)
        return false;

    #ifdef __EMSCRIPTEN__
    // In Emscripten, the surface is created from a canvas selector.
    WGPUEmscriptenSurfaceSourceCanvasHTMLSelector canvas_desc{};
    canvas_desc.chain.sType = WGPUSType_EmscriptenSurfaceSourceCanvasHTMLSelector;
    canvas_desc.selector    = WGPU_LABEL(static_cast<const char*>(native_window));

    WGPUSurfaceDescriptor desc{};
    desc.nextInChain = &canvas_desc.chain;
    surface_         = wgpuInstanceCreateSurface(instance_, &desc);
    #else
        // On native platforms, native_window is a GLFWwindow*.  Build the
        // platform surface source struct from GLFW native accessors.
        #ifdef SPECTRA_USE_GLFW
    auto* glfw_win = static_cast<GLFWwindow*>(native_window);

            #ifdef __linux__
    WGPUSurfaceSourceXlibWindow x11_src{};
    x11_src.chain.sType = WGPUSType_SurfaceSourceXlibWindow;
    x11_src.display     = glfwGetX11Display();
    x11_src.window      = static_cast<uint64_t>(glfwGetX11Window(glfw_win));

    WGPUSurfaceDescriptor desc{};
    desc.nextInChain = &x11_src.chain;
    desc.label       = WGPU_LABEL("spectra-surface");
    surface_         = wgpuInstanceCreateSurface(instance_, &desc);
            #elif defined(_WIN32)
    WGPUSurfaceSourceWindowsHWND win_src{};
    win_src.chain.sType = WGPUSType_SurfaceSourceWindowsHWND;
    win_src.hinstance   = GetModuleHandle(nullptr);
    win_src.hwnd        = glfwGetWin32Window(glfw_win);

    WGPUSurfaceDescriptor desc{};
    desc.nextInChain = &win_src.chain;
    desc.label       = WGPU_LABEL("spectra-surface");
    surface_         = wgpuInstanceCreateSurface(instance_, &desc);
            #elif defined(__APPLE__)
    // macOS requires a CAMetalLayer — would need Obj-C bridging.
    (void)glfw_win;
    return false;
            #else
    (void)glfw_win;
    return false;
            #endif
        #else
    (void)native_window;
    return false;
        #endif   // SPECTRA_USE_GLFW
    #endif       // __EMSCRIPTEN__

    return surface_ != nullptr;
}

bool WebGPUBackend::create_swapchain(uint32_t width, uint32_t height)
{
    if (!device_ || !surface_ || width == 0 || height == 0)
        return false;

    // Query surface capabilities to find the preferred format.
    WGPUSurfaceCapabilities caps{};
    WGPUStatus              cap_status     = wgpuSurfaceGetCapabilities(surface_, adapter_, &caps);
    WGPUTextureFormat       surface_format = WGPUTextureFormat_BGRA8Unorm;   // fallback
    if (cap_status == WGPUStatus_Success && caps.formatCount > 0)
    {
        surface_format = caps.formats[0];   // use the preferred format
        wgpuSurfaceCapabilitiesFreeMembers(caps);
    }

    // Unconfigure any previous surface configuration.
    if (sc_width_ > 0 && sc_height_ > 0)
        wgpuSurfaceUnconfigure(surface_);

    WGPUSurfaceConfiguration config{};
    config.device      = device_;
    config.usage       = WGPUTextureUsage_RenderAttachment;
    config.format      = surface_format;
    config.width       = width;
    config.height      = height;
    config.presentMode = WGPUPresentMode_Fifo;
    config.alphaMode   = WGPUCompositeAlphaMode_Auto;

    // Store for pipeline creation
    surface_format_ = static_cast<uint32_t>(surface_format);

    wgpuSurfaceConfigure(surface_, &config);

    sc_width_  = width;
    sc_height_ = height;
    return true;
}

bool WebGPUBackend::recreate_swapchain(uint32_t width, uint32_t height)
{
    wait_idle();
    return create_swapchain(width, height);
}

bool WebGPUBackend::create_offscreen_framebuffer(uint32_t width, uint32_t height)
{
    if (!device_ || width == 0 || height == 0)
        return false;

    // Release existing resources
    if (offscreen_depth_view_)
    {
        wgpuTextureViewRelease(offscreen_depth_view_);
        offscreen_depth_view_ = nullptr;
    }
    if (offscreen_view_)
    {
        wgpuTextureViewRelease(offscreen_view_);
        offscreen_view_ = nullptr;
    }
    if (offscreen_depth_)
    {
        wgpuTextureDestroy(offscreen_depth_);
        offscreen_depth_ = nullptr;
    }
    if (offscreen_color_)
    {
        wgpuTextureDestroy(offscreen_color_);
        offscreen_color_ = nullptr;
    }

    // Color attachment
    {
        WGPUTextureDescriptor desc{};
        desc.label         = WGPU_LABEL("OffscreenColor");
        desc.usage         = WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_CopySrc;
        desc.dimension     = WGPUTextureDimension_2D;
        desc.size          = {width, height, 1};
        desc.format        = WGPUTextureFormat_RGBA8Unorm;
        desc.mipLevelCount = 1;
        desc.sampleCount   = 1;
        offscreen_color_   = wgpuDeviceCreateTexture(device_, &desc);
        if (!offscreen_color_)
            return false;
        offscreen_view_ = wgpuTextureCreateView(offscreen_color_, nullptr);
    }

    // Depth attachment
    {
        WGPUTextureDescriptor desc{};
        desc.label         = WGPU_LABEL("OffscreenDepth");
        desc.usage         = WGPUTextureUsage_RenderAttachment;
        desc.dimension     = WGPUTextureDimension_2D;
        desc.size          = {width, height, 1};
        desc.format        = WGPUTextureFormat_Depth24Plus;
        desc.mipLevelCount = 1;
        desc.sampleCount   = 1;
        offscreen_depth_   = wgpuDeviceCreateTexture(device_, &desc);
        if (!offscreen_depth_)
            return false;
        offscreen_depth_view_ = wgpuTextureCreateView(offscreen_depth_, nullptr);
    }

    offscreen_width_  = width;
    offscreen_height_ = height;
    return true;
}

// ─── Pipeline management ──────────────────────────────────────────────────────

WGPUShaderModule WebGPUBackend::create_shader_module(const char* wgsl_source) const
{
    WGPUShaderSourceWGSL wgsl{};
    wgsl.chain.sType = WGPUSType_ShaderSourceWGSL;
    wgsl.code        = WGPU_LABEL(wgsl_source);

    WGPUShaderModuleDescriptor desc{};
    desc.nextInChain = &wgsl.chain;
    return wgpuDeviceCreateShaderModule(device_, &desc);
}

WGPUPipelineLayout WebGPUBackend::layout_for_type(PipelineType type) const
{
    switch (type)
    {
        case PipelineType::Line:
        case PipelineType::Scatter:
        case PipelineType::ScatterColormap:
            return pl_ssbo_;

        case PipelineType::Text:
        case PipelineType::TextDepth:
            return pl_texture_;

        default:
            return pl_vertex_;
    }
}

WGPURenderPipeline WebGPUBackend::create_pipeline_for_type(PipelineType type)
{
    if (!device_)
        return nullptr;

    // Select WGSL source and configuration for this pipeline type.
    const char* wgsl_source   = nullptr;
    bool        enable_depth  = false;
    bool        line_topology = false;

    // 2D vertex attribute pipelines with vec2 position.
    struct VertexAttrVec2
    {
        uint32_t attr_count = 0;
        uint32_t stride     = 0;
    } va2;

    struct VertexAttrText
    {
        bool used = false;
    } vtext;

    switch (type)
    {
        case PipelineType::Line:
            wgsl_source = wgsl::line_wgsl;
            break;

        case PipelineType::Scatter:
            wgsl_source = wgsl::scatter_wgsl;
            break;

        case PipelineType::ScatterColormap:
            // The production Vulkan backend supports scalar-valued scatter
            // buffers. WebGPU remains an experimental 2D subset and falls
            // back to the series' uniform color in Renderer.
            return nullptr;

        case PipelineType::Grid:
            wgsl_source    = wgsl::grid_wgsl;
            line_topology  = true;
            va2.attr_count = 1;
            va2.stride     = sizeof(float) * 2;
            break;

        case PipelineType::Overlay:
            wgsl_source    = wgsl::grid_wgsl;
            va2.attr_count = 1;
            va2.stride     = sizeof(float) * 2;
            break;

        case PipelineType::StatFill:
            wgsl_source    = wgsl::stat_fill_wgsl;
            va2.attr_count = 2;
            va2.stride     = sizeof(float) * 3;
            break;

        case PipelineType::Text:
            wgsl_source = wgsl::text_wgsl;
            vtext.used  = true;
            break;

        case PipelineType::TextDepth:
            wgsl_source  = wgsl::text_wgsl;
            vtext.used   = true;
            enable_depth = true;
            break;

        case PipelineType::Heatmap:
            // Not yet implemented for WebGPU.
            return nullptr;

        default:
            // 3D pipeline types not yet implemented for WebGPU.
            return nullptr;
    }

    if (!wgsl_source)
        return nullptr;

    WGPUShaderModule shader = create_shader_module(wgsl_source);
    if (!shader)
    {
        SPECTRA_LOG_ERROR("webgpu",
                          "shader module creation failed for type {}",
                          static_cast<int>(type));
        return nullptr;
    }

    // ── Vertex state ─────────────────────────────────────────────────────────

    WGPUVertexBufferLayout vbl{};
    WGPUVertexAttribute    attrs[3]{};
    WGPUVertexState        vertex_state{};
    vertex_state.module     = shader;
    vertex_state.entryPoint = WGPU_LABEL("vs_main");

    if (va2.attr_count > 0)
    {
        // Grid / overlay: location 0 = vec2 position
        attrs[0].format         = WGPUVertexFormat_Float32x2;
        attrs[0].offset         = 0;
        attrs[0].shaderLocation = 0;

        if (va2.attr_count >= 2)
        {
            // StatFill: location 1 = float alpha
            attrs[1].format         = WGPUVertexFormat_Float32;
            attrs[1].offset         = sizeof(float) * 2;
            attrs[1].shaderLocation = 1;
        }

        vbl.arrayStride    = va2.stride;
        vbl.stepMode       = WGPUVertexStepMode_Vertex;
        vbl.attributeCount = static_cast<uint32_t>(va2.attr_count);
        vbl.attributes     = attrs;

        vertex_state.bufferCount = 1;
        vertex_state.buffers     = &vbl;
    }
    else if (vtext.used)
    {
        // Text: location 0 = vec3 position, location 1 = vec2 uv, location 2 = u32 color
        attrs[0].format         = WGPUVertexFormat_Float32x3;
        attrs[0].offset         = 0;
        attrs[0].shaderLocation = 0;

        attrs[1].format         = WGPUVertexFormat_Float32x2;
        attrs[1].offset         = sizeof(float) * 3;
        attrs[1].shaderLocation = 1;

        attrs[2].format         = WGPUVertexFormat_Uint32;
        attrs[2].offset         = sizeof(float) * 5;
        attrs[2].shaderLocation = 2;

        vbl.arrayStride    = sizeof(float) * 5 + sizeof(uint32_t);   // 24 bytes = TextVertex
        vbl.stepMode       = WGPUVertexStepMode_Vertex;
        vbl.attributeCount = 3;
        vbl.attributes     = attrs;

        vertex_state.bufferCount = 1;
        vertex_state.buffers     = &vbl;
    }
    // else: SSBO-based shaders (line/scatter) — no vertex buffers.

    // ── Fragment state ───────────────────────────────────────────────────────

    WGPUBlendComponent blend_comp{};
    blend_comp.operation = WGPUBlendOperation_Add;
    blend_comp.srcFactor = WGPUBlendFactor_SrcAlpha;
    blend_comp.dstFactor = WGPUBlendFactor_OneMinusSrcAlpha;

    WGPUBlendState blend{};
    blend.color = blend_comp;
    blend.alpha = blend_comp;

    WGPUColorTargetState color_target{};
    color_target.format =
        headless_ ? WGPUTextureFormat_RGBA8Unorm : static_cast<WGPUTextureFormat>(surface_format_);
    color_target.blend     = &blend;
    color_target.writeMask = WGPUColorWriteMask_All;

    WGPUFragmentState frag_state{};
    frag_state.module      = shader;
    frag_state.entryPoint  = WGPU_LABEL("fs_main");
    frag_state.targetCount = 1;
    frag_state.targets     = &color_target;

    // ── Depth / stencil state ────────────────────────────────────────────────

    WGPUDepthStencilState depth_state{};
    if (enable_depth)
    {
        depth_state.format            = WGPUTextureFormat_Depth24Plus;
        depth_state.depthWriteEnabled = WGPUOptionalBool_False;
        depth_state.depthCompare      = WGPUCompareFunction_LessEqual;
        depth_state.stencilFront      = {WGPUCompareFunction_Always,
                                         WGPUStencilOperation_Keep,
                                         WGPUStencilOperation_Keep,
                                         WGPUStencilOperation_Keep};
        depth_state.stencilBack       = depth_state.stencilFront;
    }

    // ── Primitive state ──────────────────────────────────────────────────────

    WGPUPrimitiveState prim{};
    prim.topology =
        line_topology ? WGPUPrimitiveTopology_LineList : WGPUPrimitiveTopology_TriangleList;
    prim.stripIndexFormat = WGPUIndexFormat_Undefined;
    prim.frontFace        = WGPUFrontFace_CCW;
    prim.cullMode         = WGPUCullMode_None;

    // ── Multisample state ────────────────────────────────────────────────────

    WGPUMultisampleState ms{};
    ms.count                  = 1;
    ms.mask                   = 0xFFFFFFFF;
    ms.alphaToCoverageEnabled = false;

    // ── Pipeline descriptor ──────────────────────────────────────────────────

    WGPURenderPipelineDescriptor desc{};
    desc.layout      = layout_for_type(type);
    desc.vertex      = vertex_state;
    desc.fragment    = &frag_state;
    desc.primitive   = prim;
    desc.multisample = ms;
    if (enable_depth)
        desc.depthStencil = &depth_state;

    WGPURenderPipeline pipeline = wgpuDeviceCreateRenderPipeline(device_, &desc);

    wgpuShaderModuleRelease(shader);
    return pipeline;
}

PipelineHandle WebGPUBackend::create_pipeline(PipelineType type)
{
    WGPURenderPipeline pipeline = create_pipeline_for_type(type);
    if (!pipeline)
        return PipelineHandle{};

    PipelineHandle h;
    h.id             = next_pipeline_id_++;
    pipelines_[h.id] = {pipeline, layout_for_type(type)};
    return h;
}

void WebGPUBackend::destroy_pipeline(PipelineHandle handle)
{
    auto it = pipelines_.find(handle.id);
    if (it != pipelines_.end())
    {
        if (it->second.pipeline)
            wgpuRenderPipelineRelease(it->second.pipeline);
        pipelines_.erase(it);
    }
}

// ─── Buffer management ────────────────────────────────────────────────────────

BufferHandle WebGPUBackend::create_buffer(BufferUsage usage, size_t size_bytes)
{
    if (!device_ || size_bytes == 0)
        return BufferHandle{};

    WGPUBufferUsage wgpu_usage = static_cast<WGPUBufferUsage>(0);
    switch (usage)
    {
        case BufferUsage::Vertex:
            wgpu_usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst;
            break;
        case BufferUsage::Index:
            wgpu_usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst;
            break;
        case BufferUsage::Uniform:
            wgpu_usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
            break;
        case BufferUsage::Storage:
            wgpu_usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst;
            break;
        case BufferUsage::Staging:
            wgpu_usage = WGPUBufferUsage_MapRead | WGPUBufferUsage_CopyDst;
            break;
    }

    // Align size to 4 bytes (WebGPU requirement).
    size_t aligned = (size_bytes + 3) & ~3ull;

    WGPUBufferDescriptor desc{};
    desc.usage            = wgpu_usage;
    desc.size             = aligned;
    desc.mappedAtCreation = false;

    WGPUBuffer buf = wgpuDeviceCreateBuffer(device_, &desc);
    if (!buf)
        return BufferHandle{};

    BufferHandle h;
    h.id           = next_buffer_id_++;
    buffers_[h.id] = {buf, aligned, usage, nullptr};
    return h;
}

void WebGPUBackend::destroy_buffer(BufferHandle handle)
{
    auto it = buffers_.find(handle.id);
    if (it == buffers_.end())
        return;

    if (it->second.bind_group)
        wgpuBindGroupRelease(it->second.bind_group);
    if (it->second.buffer)
        wgpuBufferDestroy(it->second.buffer);
    buffers_.erase(it);
}

void WebGPUBackend::upload_buffer(BufferHandle handle,
                                  const void*  data,
                                  size_t       size_bytes,
                                  size_t       offset)
{
    auto it = buffers_.find(handle.id);
    if (it == buffers_.end() || !data || size_bytes == 0)
        return;

    auto& entry = it->second;

    if (entry.usage == BufferUsage::Uniform && frame_ubo_ring_)
    {
        // Allocate the next 256-byte-aligned slot in the UBO ring buffer.
        // Each upload gets its own slot so multiple UBOs within a single
        // render pass (data-space ortho, screen-space grid/text ortho)
        // do not overwrite each other before the GPU executes the commands.
        uint32_t slot_offset = ubo_ring_write_head_;
        ubo_ring_write_head_ =
            (ubo_ring_write_head_ + WGPU_FRAME_UBO_SLOT_SIZE) % WGPU_FRAME_UBO_RING_SIZE;
        ubo_bound_offset_ = slot_offset;
        wgpuQueueWriteBuffer(queue_,
                             frame_ubo_ring_,
                             static_cast<uint64_t>(slot_offset),
                             data,
                             size_bytes);
        return;
    }

    wgpuQueueWriteBuffer(queue_, entry.buffer, static_cast<uint64_t>(offset), data, size_bytes);
}

// ─── Texture management ───────────────────────────────────────────────────────

TextureHandle WebGPUBackend::create_texture(uint32_t       width,
                                            uint32_t       height,
                                            const uint8_t* rgba_data)
{
    if (!device_ || width == 0 || height == 0 || !rgba_data)
        return TextureHandle{};

    WGPUTextureDescriptor tex_desc{};
    tex_desc.usage         = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
    tex_desc.dimension     = WGPUTextureDimension_2D;
    tex_desc.size          = {width, height, 1};
    tex_desc.format        = WGPUTextureFormat_RGBA8Unorm;
    tex_desc.mipLevelCount = 1;
    tex_desc.sampleCount   = 1;

    WGPUTexture tex = wgpuDeviceCreateTexture(device_, &tex_desc);
    if (!tex)
        return TextureHandle{};

    // Upload pixel data.
    WGPUTexelCopyTextureInfo dst{};
    dst.texture  = tex;
    dst.mipLevel = 0;
    dst.origin   = {0, 0, 0};
    dst.aspect   = WGPUTextureAspect_All;

    WGPUTexelCopyBufferLayout layout{};
    layout.offset       = 0;
    layout.bytesPerRow  = width * 4;
    layout.rowsPerImage = height;

    WGPUExtent3D extent{width, height, 1};
    wgpuQueueWriteTexture(queue_,
                          &dst,
                          rgba_data,
                          static_cast<size_t>(width) * height * 4,
                          &layout,
                          &extent);

    WGPUTextureView view = wgpuTextureCreateView(tex, nullptr);

    // Sampler (linear filtering, clamp edges for atlas).
    WGPUSamplerDescriptor smp_desc{};
    smp_desc.addressModeU  = WGPUAddressMode_ClampToEdge;
    smp_desc.addressModeV  = WGPUAddressMode_ClampToEdge;
    smp_desc.magFilter     = WGPUFilterMode_Linear;
    smp_desc.minFilter     = WGPUFilterMode_Linear;
    smp_desc.mipmapFilter  = WGPUMipmapFilterMode_Linear;
    smp_desc.maxAnisotropy = 1;   // Dawn requires >= 1 (zero-init is invalid)
    WGPUSampler smp        = wgpuDeviceCreateSampler(device_, &smp_desc);

    // Texture bind group (group 1).
    WGPUBindGroupEntry entries[2]{};
    entries[0].binding     = 0;
    entries[0].textureView = view;
    entries[1].binding     = 1;
    entries[1].sampler     = smp;

    WGPUBindGroupDescriptor bg_desc{};
    bg_desc.layout     = bgl_group1_texture_;
    bg_desc.entryCount = 2;
    bg_desc.entries    = entries;
    WGPUBindGroup bg   = wgpuDeviceCreateBindGroup(device_, &bg_desc);

    TextureHandle h;
    h.id            = next_texture_id_++;
    textures_[h.id] = {tex, view, smp, bg};
    return h;
}

void WebGPUBackend::destroy_texture(TextureHandle handle)
{
    auto it = textures_.find(handle.id);
    if (it == textures_.end())
        return;

    auto& e = it->second;
    if (e.bind_group)
        wgpuBindGroupRelease(e.bind_group);
    if (e.sampler)
        wgpuSamplerRelease(e.sampler);
    if (e.view)
        wgpuTextureViewRelease(e.view);
    if (e.texture)
        wgpuTextureDestroy(e.texture);
    textures_.erase(it);
}

// ─── Frame lifecycle ──────────────────────────────────────────────────────────

bool WebGPUBackend::begin_frame(FrameProfiler* /*profiler*/)
{
    if (!device_)
        return false;

    // Reset the UBO ring write cursor so each frame starts from slot 0.
    ubo_ring_write_head_ = 0;

    // Create the command encoder for this frame.
    WGPUCommandEncoderDescriptor enc_desc{};
    enc_desc.label = WGPU_LABEL("FrameEncoder");
    encoder_       = wgpuDeviceCreateCommandEncoder(device_, &enc_desc);
    if (!encoder_)
        return false;

    // Acquire the current surface texture view.
    if (!headless_)
    {
        WGPUSurfaceTexture surf_tex{};
        wgpuSurfaceGetCurrentTexture(surface_, &surf_tex);

        if (surf_tex.status != WGPUSurfaceGetCurrentTextureStatus_SuccessOptimal
            && surf_tex.status != WGPUSurfaceGetCurrentTextureStatus_SuccessSuboptimal)
        {
            wgpuCommandEncoderRelease(encoder_);
            encoder_ = nullptr;
            return false;
        }
        current_frame_view_ = wgpuTextureCreateView(surf_tex.texture, nullptr);
        if (!current_frame_view_)
        {
            wgpuCommandEncoderRelease(encoder_);
            encoder_ = nullptr;
            return false;
        }
    }

    return true;
}

void WebGPUBackend::end_frame(FrameProfiler* /*profiler*/)
{
    if (!encoder_)
        return;

    WGPUCommandBufferDescriptor cmd_desc{};
    WGPUCommandBuffer           cmds = wgpuCommandEncoderFinish(encoder_, &cmd_desc);

    wgpuQueueSubmit(queue_, 1, &cmds);
    wgpuCommandBufferRelease(cmds);
    wgpuCommandEncoderRelease(encoder_);
    encoder_ = nullptr;

    if (!headless_ && surface_)
        wgpuSurfacePresent(surface_);

    // Process pending Dawn callbacks (e.g., map completions, error callbacks).
    wgpuDeviceTick(device_);

    if (current_frame_view_)
    {
        wgpuTextureViewRelease(current_frame_view_);
        current_frame_view_ = nullptr;
    }
}

// ─── Render pass ─────────────────────────────────────────────────────────────

void WebGPUBackend::begin_render_pass(const Color& clear_color)
{
    if (!encoder_)
        return;

    WGPUTextureView color_view = headless_ ? offscreen_view_ : current_frame_view_;
    if (!color_view)
        return;

    WGPURenderPassColorAttachment color_att{};
    color_att.view       = color_view;
    color_att.depthSlice = WGPU_DEPTH_SLICE_UNDEFINED;
    color_att.loadOp     = WGPULoadOp_Clear;
    color_att.storeOp    = WGPUStoreOp_Store;
    color_att.clearValue = {
        static_cast<double>(clear_color.r),
        static_cast<double>(clear_color.g),
        static_cast<double>(clear_color.b),
        static_cast<double>(clear_color.a),
    };

    WGPURenderPassDescriptor rp_desc{};
    rp_desc.label                  = WGPU_LABEL("MainPass");
    rp_desc.colorAttachmentCount   = 1;
    rp_desc.colorAttachments       = &color_att;
    rp_desc.depthStencilAttachment = nullptr;

    // Attach depth if we have an offscreen depth buffer.
    WGPURenderPassDepthStencilAttachment depth_att{};
    if (headless_ && offscreen_depth_view_)
    {
        depth_att.view                 = offscreen_depth_view_;
        depth_att.depthLoadOp          = WGPULoadOp_Clear;
        depth_att.depthStoreOp         = WGPUStoreOp_Discard;
        depth_att.depthClearValue      = 1.0f;
        depth_att.depthReadOnly        = false;
        rp_desc.depthStencilAttachment = &depth_att;
    }

    pass_encoder_ = wgpuCommandEncoderBeginRenderPass(encoder_, &rp_desc);
}

void WebGPUBackend::end_render_pass()
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderEnd(pass_encoder_);
    wgpuRenderPassEncoderRelease(pass_encoder_);
    pass_encoder_ = nullptr;
}

// ─── Draw state ───────────────────────────────────────────────────────────────

void WebGPUBackend::bind_pipeline(PipelineHandle handle)
{
    if (!pass_encoder_)
    {
        static int dbg_bp = 0;
        if (dbg_bp++ < 3)
            SPECTRA_LOG_ERROR("webgpu", "bind_pipeline: no pass_encoder");
        return;
    }

    auto it = pipelines_.find(handle.id);
    if (it == pipelines_.end() || !it->second.pipeline)
    {
        static int dbg_bp2 = 0;
        if (dbg_bp2++ < 3)
            SPECTRA_LOG_ERROR("webgpu", "bind_pipeline: invalid handle id={}", handle.id);
        return;
    }

    current_pipeline_        = it->second.pipeline;
    current_pipeline_layout_ = it->second.layout;
    wgpuRenderPassEncoderSetPipeline(pass_encoder_, current_pipeline_);
}

void WebGPUBackend::bind_buffer(BufferHandle handle, uint32_t binding)
{
    if (!pass_encoder_)
        return;

    auto it = buffers_.find(handle.id);
    if (it == buffers_.end())
        return;

    auto& entry = it->second;

    if (entry.usage == BufferUsage::Uniform)
    {
        // FrameUBO: bind group 0 with dynamic offset = ubo_bound_offset_.
        // (upload_buffer stored the offset into ubo_bound_offset_)
        uint32_t dynamic_offset = ubo_bound_offset_;
        wgpuRenderPassEncoderSetBindGroup(pass_encoder_, 0, frame_bind_group_, 1, &dynamic_offset);
    }
    else if (entry.usage == BufferUsage::Storage)
    {
        // Storage buffer (SSBO): bind group 1.
        if (!entry.bind_group)
        {
            // Create and cache the bind group for this storage buffer.
            WGPUBindGroupEntry bg_entry{};
            bg_entry.binding = 0;
            bg_entry.buffer  = entry.buffer;
            bg_entry.offset  = 0;
            bg_entry.size    = entry.size;

            WGPUBindGroupDescriptor desc{};
            desc.layout      = bgl_group1_ssbo_;
            desc.entryCount  = 1;
            desc.entries     = &bg_entry;
            entry.bind_group = wgpuDeviceCreateBindGroup(device_, &desc);
        }
        if (entry.bind_group)
            wgpuRenderPassEncoderSetBindGroup(pass_encoder_, 1, entry.bind_group, 0, nullptr);
    }
    else if (entry.usage == BufferUsage::Vertex)
    {
        // Vertex buffer.
        wgpuRenderPassEncoderSetVertexBuffer(pass_encoder_, binding, entry.buffer, 0, entry.size);
    }
}

void WebGPUBackend::bind_index_buffer(BufferHandle handle)
{
    if (!pass_encoder_)
        return;

    auto it = buffers_.find(handle.id);
    if (it == buffers_.end())
        return;

    current_index_buf_ = it->second.buffer;
    wgpuRenderPassEncoderSetIndexBuffer(pass_encoder_,
                                        it->second.buffer,
                                        WGPUIndexFormat_Uint32,
                                        0,
                                        it->second.size);
}

void WebGPUBackend::bind_texture(TextureHandle handle, uint32_t /*binding*/)
{
    if (!pass_encoder_)
        return;

    auto it = textures_.find(handle.id);
    if (it == textures_.end())
        return;

    auto& entry = it->second;
    if (entry.bind_group)
        wgpuRenderPassEncoderSetBindGroup(pass_encoder_, 1, entry.bind_group, 0, nullptr);
}

void WebGPUBackend::push_constants(const SeriesPushConstants& pc)
{
    if (!pass_encoder_ || !series_pc_buf_)
        return;

    // Write series push constants to the small uniform buffer.
    wgpuQueueWriteBuffer(queue_, series_pc_buf_, 0, &pc, sizeof(pc));

    // Re-bind group 0 so the GPU sees the updated series PC data.
    // We reuse the existing frame_bind_group_; the write above is visible
    // because we submit before executing commands (WebGPU memory model).
    // Dynamic offset comes from the last bind_buffer(Uniform) call.
    uint32_t dynamic_offset = ubo_bound_offset_;
    wgpuRenderPassEncoderSetBindGroup(pass_encoder_, 0, frame_bind_group_, 1, &dynamic_offset);
}

void WebGPUBackend::set_viewport(float x, float y, float width, float height)
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderSetViewport(pass_encoder_, x, y, width, height, 0.0f, 1.0f);
}

void WebGPUBackend::set_scissor(int32_t x, int32_t y, uint32_t width, uint32_t height)
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderSetScissorRect(pass_encoder_,
                                        static_cast<uint32_t>(x < 0 ? 0 : x),
                                        static_cast<uint32_t>(y < 0 ? 0 : y),
                                        width,
                                        height);
}

void WebGPUBackend::draw(uint32_t vertex_count, uint32_t first_vertex)
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderDraw(pass_encoder_, vertex_count, 1, first_vertex, 0);
}

void WebGPUBackend::draw_instanced(uint32_t vertex_count,
                                   uint32_t instance_count,
                                   uint32_t first_vertex,
                                   uint32_t first_instance)
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderDraw(pass_encoder_,
                              vertex_count,
                              instance_count,
                              first_vertex,
                              first_instance);
}

void WebGPUBackend::draw_indexed(uint32_t index_count, uint32_t first_index, int32_t vertex_offset)
{
    if (!pass_encoder_)
        return;
    wgpuRenderPassEncoderDrawIndexed(pass_encoder_, index_count, 1, first_index, vertex_offset, 0);
}

// ─── Readback ─────────────────────────────────────────────────────────────────

bool WebGPUBackend::readback_framebuffer(uint8_t* out_rgba, uint32_t width, uint32_t height)
{
    if (!device_ || !out_rgba || width == 0 || height == 0)
        return false;
    if (!headless_ || !offscreen_color_)
        return false;

    // Create a staging buffer to read back the rendered pixels.
    size_t bytes_per_row = ((width * 4 + 255) / 256) * 256;   // 256-byte alignment
    size_t total_bytes   = bytes_per_row * height;

    WGPUBufferDescriptor stage_desc{};
    stage_desc.usage            = WGPUBufferUsage_CopyDst | WGPUBufferUsage_MapRead;
    stage_desc.size             = total_bytes;
    stage_desc.mappedAtCreation = false;
    WGPUBuffer staging          = wgpuDeviceCreateBuffer(device_, &stage_desc);
    if (!staging)
        return false;

    // Submit a copy from offscreen to staging.
    WGPUCommandEncoderDescriptor enc_desc{};
    WGPUCommandEncoder           enc = wgpuDeviceCreateCommandEncoder(device_, &enc_desc);

    WGPUTexelCopyTextureInfo src{};
    src.texture  = offscreen_color_;
    src.mipLevel = 0;
    src.origin   = {0, 0, 0};
    src.aspect   = WGPUTextureAspect_All;

    WGPUTexelCopyBufferInfo dst{};
    dst.buffer              = staging;
    dst.layout.offset       = 0;
    dst.layout.bytesPerRow  = static_cast<uint32_t>(bytes_per_row);
    dst.layout.rowsPerImage = height;

    WGPUExtent3D extent{width, height, 1};
    wgpuCommandEncoderCopyTextureToBuffer(enc, &src, &dst, &extent);

    WGPUCommandBufferDescriptor cmd_desc{};
    WGPUCommandBuffer           cmds = wgpuCommandEncoderFinish(enc, &cmd_desc);
    wgpuQueueSubmit(queue_, 1, &cmds);
    wgpuCommandBufferRelease(cmds);
    wgpuCommandEncoderRelease(enc);

    // Map the staging buffer and copy pixels.
    struct MapResult
    {
        bool done = false;
        bool ok   = false;
    } map_result;

    WGPUBufferMapCallbackInfo cb_info{};
    cb_info.mode     = WGPUCallbackMode_AllowSpontaneous;
    cb_info.callback = [](WGPUMapAsyncStatus status,
                          WGPUStringView /*message*/,
                          void* userdata1,
                          void* /*userdata2*/)
    {
        auto* r = static_cast<MapResult*>(userdata1);
        r->ok   = (status == WGPUMapAsyncStatus_Success);
        r->done = true;
    };
    cb_info.userdata1 = &map_result;

    wgpuBufferMapAsync(staging, WGPUMapMode_Read, 0, total_bytes, cb_info);

    // Spin until the map completes.
    while (!map_result.done)
        wgpuInstanceProcessEvents(instance_);

    if (!map_result.ok)
    {
        wgpuBufferDestroy(staging);
        return false;
    }

    const uint8_t* mapped =
        static_cast<const uint8_t*>(wgpuBufferGetConstMappedRange(staging, 0, total_bytes));

    if (mapped)
    {
        // Copy rows, removing padding.
        for (uint32_t row = 0; row < height; ++row)
        {
            std::memcpy(out_rgba + row * width * 4, mapped + row * bytes_per_row, width * 4);
        }
    }

    wgpuBufferUnmap(staging);
    wgpuBufferDestroy(staging);
    return mapped != nullptr;
}

// ─── Swapchain queries ────────────────────────────────────────────────────────

uint32_t WebGPUBackend::swapchain_width() const
{
    return headless_ ? offscreen_width_ : sc_width_;
}

uint32_t WebGPUBackend::swapchain_height() const
{
    return headless_ ? offscreen_height_ : sc_height_;
}

}   // namespace spectra

#endif   // SPECTRA_USE_WEBGPU
