// spectra_nav_rail.cpp — Navigation rail implementation.

#include "spectra_nav_rail.hpp"
#include "spectra_nav_button.hpp"
#include "spectra_design_tokens.hpp"

#include <QPaintEvent>
#include <QPainter>
#include <QVBoxLayout>

namespace spectra::adapters::qt
{

struct NavItem
{
    const char* icon;
    const char* label;
    const char* shortcut;
};

// SpectraIcons.ttf is the small, repository-owned PUA font generated by
// tools/generate_icon_font.py. Do not pass Font Awesome codepoints here: the
// Qt frontend does not load the ImGui Font Awesome atlas and those glyphs
// render as blanks.
static const NavItem nav_items[] = {
    {"\uE00B", "Select",    "V"},  // Crosshair
    {"\uE009", "Pan",       "H"},  // Hand
    {"\uE008", "Zoom",      "Z"},  // ZoomIn
    {"\uE00A", "Measure",   "M"},  // Ruler
    {"\uE04B", "Annotate",  "A"},  // Edit
    {"\uE003", "ROI",       "R"},  // Axes / selection region
    {"\uE00C", "Markers",   "K"},  // Pin
    {"\uE004", "Transform", "T"},  // Wrench
    {"\uE003", "Inspector", "I"},  // Inspector controls
    {"\uE03A", "Timeline",  "L"},  // Clock
    {"\uE001", "Curve Editor", "C"}, // Curve chart
    {"\uE004", "Plugins",   "P"},  // Plugin tools
    {"\uE031", "Topics",    "O"},  // Live chart
    {"\uE006", "Settings",  ","},  // Settings
    {"\uE007", "Help",      "?"},  // Help
};

static constexpr int nav_item_count = sizeof(nav_items) / sizeof(nav_items[0]);

SpectraNavRail::~SpectraNavRail() = default;

SpectraNavRail::SpectraNavRail(QWidget* parent)
    : QWidget(parent)
{
    setAttribute(Qt::WA_StyledBackground, true);
    setFixedWidth(spectra_geometry().nav_rail_width);

    layout_ = new QVBoxLayout(this);
    layout_->setContentsMargins(4, 8, 4, 8);
    layout_->setSpacing(2);

    build_buttons();

    // Set Pan as default active
    set_active_tool(1);
}

void SpectraNavRail::build_buttons()
{
    for (int i = 0; i < nav_item_count; ++i)
    {
        auto* btn = new SpectraNavButton(
            QString::fromUtf8(nav_items[i].icon),
            QString::fromUtf8(nav_items[i].label),
            QString::fromUtf8(nav_items[i].shortcut),
            this);

        const int index = i;
        connect(btn, &SpectraNavButton::clicked, this, [this, index]()
        {
            set_active_tool(index);
            emit tool_selected(index);
        });

        layout_->addWidget(btn);
        buttons_.append(btn);
    }

    layout_->addStretch();
}

void SpectraNavRail::set_active_tool(int tool_index)
{
    active_ = tool_index;
    for (int i = 0; i < buttons_.size(); ++i)
        buttons_[i]->set_active(i == tool_index);
}

void SpectraNavRail::set_compact_mode(bool compact)
{
    compact_ = compact;
    const auto& g = spectra_geometry();
    setFixedWidth(compact ? g.nav_rail_width_compact : g.nav_rail_width);

    for (auto* btn : buttons_)
        btn->set_compact_mode(compact);
}

int SpectraNavRail::width_hint() const
{
    const auto& g = spectra_geometry();
    return compact_ ? g.nav_rail_width_compact : g.nav_rail_width;
}

}   // namespace spectra::adapters::qt
